controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# the route name
app_store_list:
    path: /list
    controller: App\Controller\ListController::number

app_store_description:
    path: /description
    controller: App\Controller\DescriptionController::by_number