controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# the route name is not important yet
app_store:
    path: /list
    controller: App\Controller\ListController::number